;;; emms-config --- My emacs config for emms
;;; Commentary:
;;; Best mediaplayer out there
;;; Code:
(use-package emms
  :ensure t
  :config (require 'emms-setup)
  (emms-all)
  (emms-default-players)
  (setq emms-source-file-default-directory "~/Music/")

  (global-set-key (kbd "<f6>") 'emms-previous)
  (global-set-key (kbd "<f8>") 'emms-next)
  (global-set-key (kbd "<S-f6>") 'emms-seek-backward)
  (global-set-key (kbd "<S-f8>") 'emms-seek-forward)
  (global-set-key (kbd "<f7>") 'emms-pause)
  (global-set-key (kbd "<S-f7>") 'emms-stop)

  (evil-set-initial-state 'emms-playlist-mode 'normal)
  (evil-set-initial-state 'emms-browser-mode 'normal)

  (defalias 'emms 'emms-smart-browse)
  (defalias 'music 'emms-smart-browse)
  (defalias 'music-pause-play 'emms-pause)
  (defalias 'music-stop 'emms-stop)
  (defalias 'music-next 'emms-next)
  (defalias 'music-prev 'emms-previous)
  (defalias 'music-forward 'emms-seek-forward)
  (defalias 'music-backward 'emms-seek-backward)
  (defalias 'emms-forward 'emms-seek-forward)
  (defalias 'emms-backward 'emms-seek-backward)
  (defalias 'music-seek-forward 'emms-seek-forward)
  (defalias 'music-seek-backward 'emms-seek-backward)
  (defalias 'music-previous 'emms-previous)
  (defalias 'emms-repeat-track 'emms-toggle-repeat-track)
  (defalias 'music-repeat-track 'emms-toggle-repeat-track)
  (defalias 'emms-repeat-playlist 'emms-toggle-repeat-playlist)
  (defalias 'music-repeat-playlist 'emms-toggle-repeat-playlist)
  (defalias 'emms-playlist 'emms-browser-display-playlist)
  (defalias 'music-playlist 'emms-browser-display-playlist)
  (defalias 'tag-editor 'emms-tag-editor-edit)
  (defalias 'tag-edit 'emms-tag-editor-edit)
  (defalias 'music-tag-editor 'emms-tag-editor-edit)
  (defalias 'music-tag-edit 'emms-tag-editor-edit)
  (defalias 'emms-tag-editor 'emms-tag-editor-edit)
  (defalias 'emms-tag-edit 'emms-tag-editor-edit)
  
  (evil-define-key 'normal emms-browser-mode-map (kbd "o") #'emms-add-directory-tree)
  (evil-define-key 'normal emms-browser-mode-map (kbd "O") #'emms-add-file)
  (evil-define-key 'normal emms-browser-mode-map (kbd "C-o") #'emms-add-playlist)
  ;; (evil-define-key 'normal emms-browser-mode-map (kbd "M-o") #'helm-emms)
  (evil-define-key 'normal emms-browser-mode-map (kbd "k") #'emms-browser-clear-playlist)
  (evil-define-key 'normal emms-browser-mode-map (kbd "C-<delete>") #'emms-browser-clear-playlist)
  (evil-define-key 'normal emms-browser-mode-map (kbd "1") #'emms-browse-by-genre)
  (evil-define-key 'normal emms-browser-mode-map (kbd "2") #'emms-browse-by-artist)
  (evil-define-key 'normal emms-browser-mode-map (kbd "3") #'emms-browse-by-album)
  (evil-define-key 'normal emms-browser-mode-map (kbd "4") #'emms-browse-by-year)
  (evil-define-key 'normal emms-browser-mode-map (kbd "5") #'emms-browse-by-composer)
  (evil-define-key 'normal emms-browser-mode-map (kbd "6") #'emms-browse-by-performer)
  (evil-define-key 'normal emms-browser-mode-map (kbd "f") #'emms-browser-search-by-title)
  (evil-define-key 'normal emms-browser-mode-map (kbd "p") #'emms-browser-display-playlist)
  (evil-define-key 'normal emms-browser-mode-map (kbd "F") #'emms-browser-search-by-album)
  (evil-define-key 'normal emms-browser-mode-map (kbd "C-f") #'emms-browser-search-by-artist)
  (evil-define-key 'normal emms-browser-mode-map (kbd "C-S-f") #'emms-browser-search-by-composer)
  (evil-define-key 'normal emms-browser-mode-map (kbd "<return>") #'emms-browser-add-tracks)
  (evil-define-key 'normal emms-browser-mode-map (kbd "\\") #'emms-browser-add-tracks-and-play)
  (evil-define-key 'normal emms-browser-mode-map (kbd "<C-SPC>") #'emms-browser-expand-to-level-4)
  (evil-define-key 'normal emms-browser-mode-map (kbd "SPC") #'emms-browser-expand-one-level)
  (evil-define-key 'normal emms-browser-mode-map (kbd "M-SPC") #'emms-browser-collapse-all)

  (evil-define-key 'normal emms-browser-mode-map (kbd "m") #'emms-mark-forward)
  (evil-define-key 'normal emms-browser-mode-map (kbd "M") #'emms-mark-all)
  (evil-define-key 'normal emms-browser-mode-map (kbd "C-m") #'emms-mark-regexp)
  (evil-define-key 'normal emms-browser-mode-map (kbd "U") #'emms-mark-unmark-all)
  (evil-define-key 'normal emms-browser-mode-map (kbd "u") #'emms-mark-unmark-forward)
  
  (define-key emms-playlist-mode-map (kbd "k") nil)
  (define-key emms-playlist-mode-map (kbd "r") nil)
  (define-key emms-playlist-mode-map (kbd "D") nil)
  (define-key emms-playlist-mode-map (kbd "E") nil)
  (define-key emms-playlist-mode-map (kbd "s") nil)
  (define-key emms-playlist-mode-map (kbd "P") nil)
  (define-key emms-playlist-mode-map (kbd "n") nil)
  (define-key emms-playlist-mode-map (kbd "p") nil)
  
  (evil-define-key 'normal emms-playlist-mode-map (kbd "<return>") #'emms-pause)
  (evil-define-key 'normal emms-playlist-mode-map (kbd ",") #'emms-previous)
  (evil-define-key 'normal emms-playlist-mode-map (kbd ".") #'emms-next)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "<C-left>") #'emms-previous)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "<C-right>") #'emms-next)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "k") #'emms-playlist-mode-current-kill)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "K") #'emms-mark-delete-marked-tracks)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "<delete>") #'emms-playlist-mode-kill-track)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "<C-delete>") #'emms-mark-delete-marked-tracks)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "<C-Home>") #'emms-playlist-mode-first)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "<C-End>") #'emms-playlist-mode-last)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "s") #'emms-playlist-save)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "m") #'emms-mark-forward)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "M") #'emms-mark-all)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "C-m") #'emms-mark-regexp)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "o") #'emms-add-playlist)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "n") #'emms-playlist-new)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "U") #'emms-mark-unmark-all)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "u") #'emms-mark-unmark-forward)
  (evil-define-key 'normal emms-playlist-mode-map (kbd "t") #'emms-tag-editor-edit)

  ;; (evil-define-key 'normal emms-browser-mode-map (kbd "<M-RET>") #'make-new-buffer)
  ;; (evil-define-key 'normal emms-playlist-mode-map (kbd "<M-RET>") #'make-new-buffer)
  
  (require 'emms-playing-time)
  (emms-playing-time 1)
  
  (defun kill-emms ()
	(interactive)
	(flet ((kill-buffer-ask (buffer) (kill-buffer buffer)))
	  (kill-matching-buffers "*EMMS Playlist*")
	  (kill-matching-buffers "*EMMS-TAGS*")
	  (kill-matching-buffers "EMMS")
	  (kill-matching-buffers "Browsing by:")))
  (defalias 'emms-kill 'kill-emms)
  (defalias 'music-kill 'kill-emms)
  (defalias 'kill-music 'kill-emms))
;; (use-package helm-emms
;;   :ensure t
;;   :after emms)
(use-package emms-info-mediainfo
  :ensure t
  :config (add-to-list 'emms-info-functions #'emms-info-mediainfo)
  :after emms)
(use-package emms-player-mpv
  :ensure t
  :config (add-to-list 'emms-player-list 'emms-player-mpv)
  :after emms)
(use-package emms-player-simple-mpv
  :ensure t
  :config (require 'emms-player-simple-mpv-e.g.time-display))
