;;; mu4e-config.el --- mu4e conf

;;; Copyright (C) 2017 scvh-man
;;; Author: scvh-man
;;; License: http://www.gnu.org/licenses/gpl-3.0.en.html

;;; Commentary:
;;; Code:
(add-to-list 'load-path "/usr/share/emacs/site-lisp/mu4e")
(require 'mu4e)
(setq starttls-use-gnutls t)
(setq message-send-mail-function 'smtpmail-send-it)
(setq smtpmail-debug-info t)
(setq mu4e-show-images t)
(setq mu4e-split-view nil)
(when (fboundp 'imagemagick-register-types)
  (imagemagick-register-types))
(setq mu4e-sent-messages-behavior 'delete)
(setq mu4e-get-mail-command "offlineimap")
(setq mu4e-contexts
	  `( ,(make-mu4e-context
		   :name "Gmail"
		   :enter-func (lambda () (mu4e-message "Entering Gmail context"))
		   :leave-func (lambda () (mu4e-message "Leaving Gmail context"))
		   :vars '((user-mail-address . "scvhapps@gmail.com")
				   (smtpmail-smtp-server . "smtp.gmail.com")
				   (smtpmail-smtp-service . 587)
				   (smtpmail-smtp-user . "scvhapps")
				   (user-full-name . "Ivan Pigan")
				   (user-mail-address . "scvhapps@gmail.com")
				   (mail-reply-to . "scvhapps@gmail.com")
				   (mu4e-drafts-folder . "/Gmail/[Gmail].Drafts")
				   (mu4e-refile-folder . "/Gmail/Archived")
				   (mu4e-action-tags-header "X-Keywords")
				   (mu4e-sent-folder . "/Gmail/[Gmail].Sent Mail")
				   (mu4e-trash-folder . "/Gmail/[Gmail].Trash")))))
(setq mu4e-context-policy 'pick-first)
(defun mu4e-update-mail ()
  (interactive)
  (mu4e-update-mail-and-index)
  (mu4e-view-refresh))
(add-hook 'mu4e-main-mode-hook
		  (lambda ()
			(local-set-key (kbd "C-j") #'mu4e~headers-jump-to-maildir)
			(local-set-key (kbd "M-f") #'mu4e-headers-search)
			(local-set-key (kbd "C-n") #'mu4e-compose-new)
			(local-set-key (kbd "M-r") #'mu4e-update-mail)
			(local-set-key (kbd "C-j") #'mu4e~headers-jump-to-maildir)
			(local-set-key (kbd "M-\\") #'mu4e-context-switch)
			(local-set-key (kbd "M-h") #'mu4e-display-manual)
			(local-set-key (kbd "M-r") #'mu4e-update-mail-and-index)
			(local-set-key (kbd "C-q") #'mu4e-quit)))
(add-hook 'mu4e-headers-mode-hook
		  (lambda ()
			(null-all-bindings)
			(local-set-key (kbd "<M-down>") nil)
			(local-set-key (kbd "<M-up>") nil)
			(local-set-key (kbd "M-r") #'mu4e-update-mail-and-index)
			(local-set-key (kbd "C-j") #'mu4e~headers-jump-to-maildir)
			(local-set-key (kbd "C-S-n") #'mu4e-compose-reply)
			(local-set-key (kbd "C-M-n") #'mu4e-compose-forward)
			(local-set-key (kbd "C-n") #'mu4e-compose-new)
			(local-set-key (kbd "C-S-u") #'mu4e-mark-unmark-all)
			(local-set-key (kbd "C-u") #'mu4e-headers-mark-for-unmark)
			(local-set-key (kbd "C-k")  #'mu4e-headers-mark-for-trash)
			(local-set-key (kbd "<return>") #'mu4e-headers-view-message)
			(local-set-key (kbd "<delete>") #'mu4e-headers-mark-for-trash)
			(local-set-key (kbd "<deletechar>") #'mu4e-headers-mark-for-trash)
			(local-set-key (kbd "C-S-r") #'mu4e-headers-mark-for-unread)
			(local-set-key (kbd "R") #'mu4e-headers-mark-for-read)
			(local-set-key (kbd "C-b") #'mu4e-headers-search-bookmark)
			(local-set-key (kbd "C-S-b") #'mu4e-headers-search-bookmark-edit)
			(local-set-key (kbd "C-t") #'mu4e-headers-mark-for-move)
			(local-set-key (kbd "C-s") #'mu4e-headers-mark-for-move)
			(local-set-key (kbd "C-m") #'mu4e-headers-mark-for-action)
			(local-set-key (kbd "M-\\") #'mu4e-mark-execute-all)
			(local-set-key (kbd "C-S-f") #'mu4e-headers-search)
			(local-set-key (kbd "M-f") #'mu4e-headers-search-edit)
			(local-set-key (kbd ",") 'mu4e-headers-prev)
			(local-set-key (kbd ".") 'mu4e-headers-next)
			(local-set-key (kbd "<") 'mu4e-headers-prev-unread)
			(local-set-key (kbd ">") 'mu4e-headers-next-unread)
			(local-set-key (kbd "<C-up>") 'mu4e-headers-prev-unread)
			(local-set-key (kbd "<C-down>") 'mu4e-headers-next-unread)
			(local-set-key (kbd "C-,") 'mu4e-headers-prev-unread)
			(local-set-key (kbd "C-q") #'mu4e~headers-quit-buffer)
			(local-set-key (kbd "C-.") 'mu4e-headers-next-unread)))
(add-hook 'mu4e-view-mode-hook
		  (lambda ()
			(null-all-bindings)
			(local-set-key (kbd "<M-down>") nil)
			(local-set-key (kbd "<M-up>") nil)

			(local-set-key (kbd "C-q") #'mu4e~view-quit-buffer)
			(local-set-key (kbd "M-r") #'mu4e-update-mail)
			(local-set-key (kbd "C-n") #'mu4e-compose-reply)
			(local-set-key (kbd "C-M-n") #'mu4e-compose-forward)
			(local-set-key (kbd "C-S-n") #'mu4e-compose-new)
			(local-set-key (kbd "M-|") #'mu4e-view-raw-message)
			(local-set-key (kbd "M-\\") #'mu4e-view-action)
			(local-set-key (kbd "C-M-\\") #'mu4e-view-toggle-html)
			(local-set-key (kbd "C-s") #'mu4e-view-save-attachment)
			(local-set-key (kbd "M-o") #'mu4e-view-open-attachment)
			(local-set-key (kbd "M-S-o") #'mu4e-view-attachment-action)
			(local-set-key (kbd ",") #'mu4e-view-headers-prev)
			(local-set-key (kbd ".") #'mu4e-view-headers-next)
			(local-set-key (kbd "C-,") #'mu4e-view-headers-prev-unread)
			(local-set-key (kbd "C-.") #'mu4e-view-headers-next-unread)
			(local-set-key (kbd "<") #'mu4e-view-headers-prev-unread)
			(local-set-key (kbd ">") #'mu4e-view-headers-next-unread)
			(local-set-key (kbd "<delete>") #'mu4e-view-mark-for-trash)
			(local-set-key (kbd "<deletechar>") #'mu4e-view-mark-for-trash)))
(add-hook 'mu4e-index-updated-hook (lambda ()
									 (sauron-add-event
									  'mu4e
									  3
									  "Email arrived!"
									  '(lambda ()
										 (mu4e)))))
(add-hook 'mu4e-compose-mode-hook (lambda ()
									(local-set-key (kbd "M-i") #'mml-attach-file)
									(local-set-key (kbd "M-k") #'message-dont-send)
									(local-set-key (kbd "C-q") #'message-dont-send)))

(defalias 'send-email 'message-send-and-exit)
(defalias 'send-message 'message-send-and-exit)
(defalias 'attachment-email 'mml-attach-file)
(defalias 'add-attachment-email 'mml-attach-file)
(defalias 'attach-email 'mml-attach-file)
(defalias 'add-attach-email 'mml-attach-file)
(defalias 'file-email 'mml-attach-file)
(defalias 'add-file-email 'mml-attach-file)
(defalias 'attachment-mail 'mml-attach-file)
(defalias 'add-attachment-mail 'mml-attach-file)
(defalias 'attach-mail 'mml-attach-file)
(defalias 'add-attach-mail 'mml-attach-file)
(defalias 'file-mail 'mml-attach-file)
(defalias 'add-file-mail 'mml-attach-file)
(defalias 'attachment-message 'mml-attach-file)
(defalias 'add-attachment-message 'mml-attach-file)
(defalias 'attach-message 'mml-attach-file)
(defalias 'add-attach-message 'mml-attach-file)
(defalias 'file-message 'mml-attach-file)
(defalias 'add-file-message 'mml-attach-file)
(defalias 'cancel-email 'message-dont-send)
(defalias 'cancel-mail 'message-dont-send)
(defalias 'cancel-message 'message-dont-send)
(use-package mu4e-alert
  :ensure t
  :config (mu4e-alert-set-default-style 'libnotify)
  (add-hook 'after-init-hook #'mu4e-alert-enable-notifications)
  ;; (add-hook 'after-init-hook #'mu4e-alert-enable-mode-line-display))
  )
;; (mu4e-update-index)
;; (run-with-idle-timer 180 t (lambda () (mu4e-update-index)))
;;; mu4e-config.el ends here
