;;; rss-reading.el --- rss reading config

;;; Copyright (C) 2017 scvh-man
;;; Author: scvh-man
;;; License: http://www.gnu.org/licenses/gpl-3.0.en.html

;;; Commentary:
;;; Code:
(use-package elfeed
  :pin melpa-stable
  :ensure t
  :config
  (defalias 'rss 'elfeed)
  (defalias 'news 'elfeed)

  (define-key elfeed-search-mode-map (kbd "<") nil)
  (define-key elfeed-search-mode-map (kbd ">") nil)
  (define-key elfeed-search-mode-map (kbd "A") nil)
  (define-key elfeed-search-mode-map (kbd "B") nil)
  (define-key elfeed-search-mode-map (kbd "C") nil)
  (define-key elfeed-search-mode-map (kbd "D") nil)
  (define-key elfeed-search-mode-map (kbd "E") nil)
  (define-key elfeed-search-mode-map (kbd "F") nil)
  (define-key elfeed-search-mode-map (kbd "G") nil)
  (define-key elfeed-search-mode-map (kbd "H") nil)
  (define-key elfeed-search-mode-map (kbd "I") nil)
  (define-key elfeed-search-mode-map (kbd "J") nil)
  (define-key elfeed-search-mode-map (kbd "K") nil)
  (define-key elfeed-search-mode-map (kbd "L") nil)
  (define-key elfeed-search-mode-map (kbd "M") nil)
  (define-key elfeed-search-mode-map (kbd "N") nil)
  (define-key elfeed-search-mode-map (kbd "O") nil)
  (define-key elfeed-search-mode-map (kbd "P") nil)
  (define-key elfeed-search-mode-map (kbd "Q") nil)
  (define-key elfeed-search-mode-map (kbd "R") nil)
  (define-key elfeed-search-mode-map (kbd "S") nil)
  (define-key elfeed-search-mode-map (kbd "T") nil)
  (define-key elfeed-search-mode-map (kbd "U") nil)
  (define-key elfeed-search-mode-map (kbd "V") nil)
  (define-key elfeed-search-mode-map (kbd "W") nil)
  (define-key elfeed-search-mode-map (kbd "X") nil)
  (define-key elfeed-search-mode-map (kbd "Y") nil)
  (define-key elfeed-search-mode-map (kbd "Z") nil)
  (define-key elfeed-search-mode-map (kbd "a") nil)
  (define-key elfeed-search-mode-map (kbd "b") nil)
  (define-key elfeed-search-mode-map (kbd "c") nil)
  (define-key elfeed-search-mode-map (kbd "d") nil)
  (define-key elfeed-search-mode-map (kbd "e") nil)
  (define-key elfeed-search-mode-map (kbd "f") nil)
  (define-key elfeed-search-mode-map (kbd "g") nil)
  (define-key elfeed-search-mode-map (kbd "h") nil)
  (define-key elfeed-search-mode-map (kbd "i") nil)
  (define-key elfeed-search-mode-map (kbd "j") nil)
  (define-key elfeed-search-mode-map (kbd "k") nil)
  (define-key elfeed-search-mode-map (kbd "l") nil)
  (define-key elfeed-search-mode-map (kbd "m") nil)
  (define-key elfeed-search-mode-map (kbd "n") nil)
  (define-key elfeed-search-mode-map (kbd "o") nil)
  (define-key elfeed-search-mode-map (kbd "p") nil)
  (define-key elfeed-search-mode-map (kbd "q") nil)
  (define-key elfeed-search-mode-map (kbd "r") nil)
  (define-key elfeed-search-mode-map (kbd "s") nil)
  (define-key elfeed-search-mode-map (kbd "t") nil)
  (define-key elfeed-search-mode-map (kbd "u") nil)
  (define-key elfeed-search-mode-map (kbd "v") nil)
  (define-key elfeed-search-mode-map (kbd "w") nil)
  (define-key elfeed-search-mode-map (kbd "x") nil)
  (define-key elfeed-search-mode-map (kbd "y") nil)
  (define-key elfeed-search-mode-map (kbd "z") nil)
  (define-key elfeed-search-mode-map (kbd ":a") nil)
  (define-key elfeed-search-mode-map (kbd ":b") nil)
  (define-key elfeed-search-mode-map (kbd ":c") nil)
  (define-key elfeed-search-mode-map (kbd ":d") nil)
  (define-key elfeed-search-mode-map (kbd ":e") nil)
  (define-key elfeed-search-mode-map (kbd ":f") nil)
  (define-key elfeed-search-mode-map (kbd ":g") nil)
  (define-key elfeed-search-mode-map (kbd ":h") nil)
  (define-key elfeed-search-mode-map (kbd ":i") nil)
  (define-key elfeed-search-mode-map (kbd ":j") nil)
  (define-key elfeed-search-mode-map (kbd ":k") nil)
  (define-key elfeed-search-mode-map (kbd ":l") nil)
  (define-key elfeed-search-mode-map (kbd ":m") nil)
  (define-key elfeed-search-mode-map (kbd ":n") nil)
  (define-key elfeed-search-mode-map (kbd ":o") nil)
  (define-key elfeed-search-mode-map (kbd ":p") nil)
  (define-key elfeed-search-mode-map (kbd ":q") nil)
  (define-key elfeed-search-mode-map (kbd ":r") nil)
  (define-key elfeed-search-mode-map (kbd ":s") nil)
  (define-key elfeed-search-mode-map (kbd ":t") nil)
  (define-key elfeed-search-mode-map (kbd ":u") nil)
  (define-key elfeed-search-mode-map (kbd ":v") nil)
  (define-key elfeed-search-mode-map (kbd ":w") nil)
  (define-key elfeed-search-mode-map (kbd ":x") nil)
  (define-key elfeed-search-mode-map (kbd ":y") nil)
  (define-key elfeed-search-mode-map (kbd ":z") nil)
  (define-key elfeed-search-mode-map (kbd ":A") nil)
  (define-key elfeed-search-mode-map (kbd ":B") nil)
  (define-key elfeed-search-mode-map (kbd ":C") nil)
  (define-key elfeed-search-mode-map (kbd ":D") nil)
  (define-key elfeed-search-mode-map (kbd ":E") nil)
  (define-key elfeed-search-mode-map (kbd ":F") nil)
  (define-key elfeed-search-mode-map (kbd ":G") nil)
  (define-key elfeed-search-mode-map (kbd ":H") nil)
  (define-key elfeed-search-mode-map (kbd ":I") nil)
  (define-key elfeed-search-mode-map (kbd ":J") nil)
  (define-key elfeed-search-mode-map (kbd ":K") nil)
  (define-key elfeed-search-mode-map (kbd ":L") nil)
  (define-key elfeed-search-mode-map (kbd ":M") nil)
  (define-key elfeed-search-mode-map (kbd ":N") nil)
  (define-key elfeed-search-mode-map (kbd ":O") nil)
  (define-key elfeed-search-mode-map (kbd ":P") nil)
  (define-key elfeed-search-mode-map (kbd ":Q") nil)
  (define-key elfeed-search-mode-map (kbd ":R") nil)
  (define-key elfeed-search-mode-map (kbd ":S") nil)
  (define-key elfeed-search-mode-map (kbd ":T") nil)
  (define-key elfeed-search-mode-map (kbd ":U") nil)
  (define-key elfeed-search-mode-map (kbd ":V") nil)
  (define-key elfeed-search-mode-map (kbd ":W") nil)
  (define-key elfeed-search-mode-map (kbd ":X") nil)
  (define-key elfeed-search-mode-map (kbd ":Y") nil)
  (define-key elfeed-search-mode-map (kbd ":Z") nil)
  (define-key elfeed-search-mode-map (kbd "+") nil)
  (define-key elfeed-search-mode-map (kbd "-") nil)

  (define-key elfeed-show-mode-map (kbd "<") nil)
  (define-key elfeed-show-mode-map (kbd ">") nil)
  (define-key elfeed-show-mode-map (kbd "A") nil)
  (define-key elfeed-show-mode-map (kbd "B") nil)
  (define-key elfeed-show-mode-map (kbd "C") nil)
  (define-key elfeed-show-mode-map (kbd "D") nil)
  (define-key elfeed-show-mode-map (kbd "E") nil)
  (define-key elfeed-show-mode-map (kbd "F") nil)
  (define-key elfeed-show-mode-map (kbd "G") nil)
  (define-key elfeed-show-mode-map (kbd "H") nil)
  (define-key elfeed-show-mode-map (kbd "I") nil)
  (define-key elfeed-show-mode-map (kbd "J") nil)
  (define-key elfeed-show-mode-map (kbd "K") nil)
  (define-key elfeed-show-mode-map (kbd "L") nil)
  (define-key elfeed-show-mode-map (kbd "M") nil)
  (define-key elfeed-show-mode-map (kbd "N") nil)
  (define-key elfeed-show-mode-map (kbd "O") nil)
  (define-key elfeed-show-mode-map (kbd "P") nil)
  (define-key elfeed-show-mode-map (kbd "Q") nil)
  (define-key elfeed-show-mode-map (kbd "R") nil)
  (define-key elfeed-show-mode-map (kbd "S") nil)
  (define-key elfeed-show-mode-map (kbd "T") nil)
  (define-key elfeed-show-mode-map (kbd "U") nil)
  (define-key elfeed-show-mode-map (kbd "V") nil)
  (define-key elfeed-show-mode-map (kbd "W") nil)
  (define-key elfeed-show-mode-map (kbd "X") nil)
  (define-key elfeed-show-mode-map (kbd "Y") nil)
  (define-key elfeed-show-mode-map (kbd "Z") nil)
  (define-key elfeed-show-mode-map (kbd "a") nil)
  (define-key elfeed-show-mode-map (kbd "b") nil)
  (define-key elfeed-show-mode-map (kbd "c") nil)
  (define-key elfeed-show-mode-map (kbd "d") nil)
  (define-key elfeed-show-mode-map (kbd "e") nil)
  (define-key elfeed-show-mode-map (kbd "f") nil)
  (define-key elfeed-show-mode-map (kbd "g") nil)
  (define-key elfeed-show-mode-map (kbd "h") nil)
  (define-key elfeed-show-mode-map (kbd "i") nil)
  (define-key elfeed-show-mode-map (kbd "j") nil)
  (define-key elfeed-show-mode-map (kbd "k") nil)
  (define-key elfeed-show-mode-map (kbd "l") nil)
  (define-key elfeed-show-mode-map (kbd "m") nil)
  (define-key elfeed-show-mode-map (kbd "n") nil)
  (define-key elfeed-show-mode-map (kbd "o") nil)
  (define-key elfeed-show-mode-map (kbd "p") nil)
  (define-key elfeed-show-mode-map (kbd "q") nil)
  (define-key elfeed-show-mode-map (kbd "r") nil)
  (define-key elfeed-show-mode-map (kbd "s") nil)
  (define-key elfeed-show-mode-map (kbd "t") nil)
  (define-key elfeed-show-mode-map (kbd "u") nil)
  (define-key elfeed-show-mode-map (kbd "v") nil)
  (define-key elfeed-show-mode-map (kbd "w") nil)
  (define-key elfeed-show-mode-map (kbd "x") nil)
  (define-key elfeed-show-mode-map (kbd "y") nil)
  (define-key elfeed-show-mode-map (kbd "z") nil)
  (define-key elfeed-show-mode-map (kbd ":a") nil)
  (define-key elfeed-show-mode-map (kbd ":b") nil)
  (define-key elfeed-show-mode-map (kbd ":c") nil)
  (define-key elfeed-show-mode-map (kbd ":d") nil)
  (define-key elfeed-show-mode-map (kbd ":e") nil)
  (define-key elfeed-show-mode-map (kbd ":f") nil)
  (define-key elfeed-show-mode-map (kbd ":g") nil)
  (define-key elfeed-show-mode-map (kbd ":h") nil)
  (define-key elfeed-show-mode-map (kbd ":i") nil)
  (define-key elfeed-show-mode-map (kbd ":j") nil)
  (define-key elfeed-show-mode-map (kbd ":k") nil)
  (define-key elfeed-show-mode-map (kbd ":l") nil)
  (define-key elfeed-show-mode-map (kbd ":m") nil)
  (define-key elfeed-show-mode-map (kbd ":n") nil)
  (define-key elfeed-show-mode-map (kbd ":o") nil)
  (define-key elfeed-show-mode-map (kbd ":p") nil)
  (define-key elfeed-show-mode-map (kbd ":q") nil)
  (define-key elfeed-show-mode-map (kbd ":r") nil)
  (define-key elfeed-show-mode-map (kbd ":s") nil)
  (define-key elfeed-show-mode-map (kbd ":t") nil)
  (define-key elfeed-show-mode-map (kbd ":u") nil)
  (define-key elfeed-show-mode-map (kbd ":v") nil)
  (define-key elfeed-show-mode-map (kbd ":w") nil)
  (define-key elfeed-show-mode-map (kbd ":x") nil)
  (define-key elfeed-show-mode-map (kbd ":y") nil)
  (define-key elfeed-show-mode-map (kbd ":z") nil)
  (define-key elfeed-show-mode-map (kbd ":A") nil)
  (define-key elfeed-show-mode-map (kbd ":B") nil)
  (define-key elfeed-show-mode-map (kbd ":C") nil)
  (define-key elfeed-show-mode-map (kbd ":D") nil)
  (define-key elfeed-show-mode-map (kbd ":E") nil)
  (define-key elfeed-show-mode-map (kbd ":F") nil)
  (define-key elfeed-show-mode-map (kbd ":G") nil)
  (define-key elfeed-show-mode-map (kbd ":H") nil)
  (define-key elfeed-show-mode-map (kbd ":I") nil)
  (define-key elfeed-show-mode-map (kbd ":J") nil)
  (define-key elfeed-show-mode-map (kbd ":K") nil)
  (define-key elfeed-show-mode-map (kbd ":L") nil)
  (define-key elfeed-show-mode-map (kbd ":M") nil)
  (define-key elfeed-show-mode-map (kbd ":N") nil)
  (define-key elfeed-show-mode-map (kbd ":O") nil)
  (define-key elfeed-show-mode-map (kbd ":P") nil)
  (define-key elfeed-show-mode-map (kbd ":Q") nil)
  (define-key elfeed-show-mode-map (kbd ":R") nil)
  (define-key elfeed-show-mode-map (kbd ":S") nil)
  (define-key elfeed-show-mode-map (kbd ":T") nil)
  (define-key elfeed-show-mode-map (kbd ":U") nil)
  (define-key elfeed-show-mode-map (kbd ":V") nil)
  (define-key elfeed-show-mode-map (kbd ":W") nil)
  (define-key elfeed-show-mode-map (kbd ":X") nil)
  (define-key elfeed-show-mode-map (kbd ":Y") nil)
  (define-key elfeed-show-mode-map (kbd ":Z") nil)
  (define-key elfeed-show-mode-map (kbd "+") nil)
  (define-key elfeed-show-mode-map (kbd "-") nil)

  (define-key elfeed-search-mode-map (kbd "M-f") #'elfeed-search-live-filter)
  (define-key elfeed-search-mode-map (kbd "M-y") #'elfeed-search-yank)
  (define-key elfeed-search-mode-map (kbd "M-o") #'elfeed-search-browse-url)
  (define-key elfeed-search-mode-map (kbd "C-S-t") #'elfeed-search-tag-all)
  (define-key elfeed-search-mode-map (kbd "C-S-u") #'elfeed-search-untag-all)

  (define-key elfeed-show-mode-map (kbd "M-r") #'elfeed-show-refresh)
  (define-key elfeed-show-mode-map (kbd "M-o") #'elfeed-show-visit)
  (define-key elfeed-show-mode-map (kbd "M-y") #'elfeed-show-yank)
  ;; (define-key elfeed-show-mode-map (kbd "q") #'kill-this-buffer)
  (define-key elfeed-show-mode-map (kbd "M-t") #'elfeed-show-tag)
  (define-key elfeed-show-mode-map (kbd "M-S-t") #'elfeed-show-untag)
  (define-key elfeed-show-mode-map (kbd ".") #'elfeed-show-next)
  (define-key elfeed-show-mode-map (kbd ",") #'elfeed-show-prev)
  (defun elfeed-mark-all-read ()
	(interactive)
	(elfeed-untag elfeed-search-entries 'unread)
	(elfeed-search-update :force)
	(elfeed-db-save))
  (define-key elfeed-search-mode-map (kbd "R") #'elfeed-mark-all-read)
  ;;from here http://pragmaticemacs.com/emacs/star-and-unstar-articles-in-elfeed/
  (defun bjm/elfeed-star ()
	"Apply starred to all selected entries."
	(interactive )
	(let* ((entries (elfeed-search-selected))
		   (tag (intern "starred")))

	  (cl-loop for entry in entries do (elfeed-tag entry tag))
	  (mapc #'elfeed-search-update-entry entries)
	  (unless (use-region-p) (forward-line))))
  (defun bjm/elfeed-unstar ()
	"Remove starred tag from all selected entries."
	(interactive )
	(let* ((entries (elfeed-search-selected))
		   (tag (intern "starred")))

	  (cl-loop for entry in entries do (elfeed-untag entry tag))
	  (mapc #'elfeed-search-update-entry entries)
	  (unless (use-region-p) (forward-line))))
  (defface elfeed-search-starred-title-face
	'((t :foreground "#ff0000"))
	"Marks a starred Elfeed entry.")
  (push '(starred elfeed-search-starred-title-face) elfeed-search-face-alist)
  (define-key elfeed-search-mode-map (kbd "C-s") #'bjm/elfeed-star)
  (define-key elfeed-search-mode-map (kbd "C-M-s") #'bjm/elfeed-unstar))

(use-package elfeed-org
  :ensure t
  :config (elfeed-org))
;;; rss-reading.el ends here
