# Custom alias for listing files when moving to directory
if test -e /usr/bin/proxychains
	alias proxy 'proxychains'

	alias curl 'proxychains /usr/bin/curl'
	alias wget 'proxychains /usr/bin/wget'
	alias yadm 'proxychains /usr/bin/yadm'
	alias ssh 'proxychains /usr/bin/ssh'
	alias w3m 'proxychains /usr/bin/w3m'
	alias telnet 'proxychains /usr/bin/telnet'
	alias gem 'proxychains gem'
	alias luarocks 'proxychains luarocks'
	alias pip 'proxychains pip'
	alias pip3 'proxychains pip3'
	alias npm 'proxychains npm'
	alias cpan 'proxychains cpan'
	alias cabal 'proxychains cabal'
	alias gopm 'proxychains ~/Go/bin/gopm'
	alias omf 'proxychains omf'
	alias sudo-gem 'sudo proxychains gem'
	alias sudo-luarocks 'sudo proxychains luarocks'
	alias sudo-pip 'sudo proxychains pip'
	alias sudo-pip3 'sudo proxychains pip3'
	alias sudo-npm 'sudo proxychains npm'
	alias sudo-cpan 'sudo proxychains cpan'
	alias sudo-cabal 'sudo proxychains cabal'
	alias sudo-gopm 'sudo proxychains ~/Go/bin/gopm'
	alias sudo-omf 'sudo proxychains omf'
	alias apt-get 'proxychains /usr/bin/apt-get'
	alias apt-cache 'proxychains /usr/bin/apt-cache'
	alias sudo-curl 'sudo proxychains /usr/bin/curl'
	alias sudo-wget 'sudo proxychains /usr/bin/wget'
	alias sudo-telnet 'sudo proxychains /usr/bin/telnet'
	alias sudo-apt-get 'sudo proxychains /usr/bin/apt-get'
	alias sudo-apt-cache 'sudo proxychains /usr/bin/apt-cache'

	alias gem-no-proxy '/usr/bin/gem'
	alias luarocks-no-proxy '/usr/bin/luarocks'
	alias pip-no-proxy '/usr/bin/pip'
	alias pip3-no-proxy '/usr/bin/pip3'
	alias npm-no-proxy '/usr/bin/npm'
	alias cpan-no-proxy '/usr/bin/cpan'
	alias cabal-no-proxy '/usr/bin/cabal'
	alias gopm-no-proxy '~/Go/bin/gopm'
	alias git-no-proxy '/usr/bin/git'
	alias yadm-no-proxy '/usr/bin/yadm'
	alias wget-no-proxy '/usr/bin/wget'
	alias telnet-no-proxy '/usr/bin/telnet'
	alias curl-no-proxy '/usr/bin/curl'
	alias apt-get-no-proxy '/usr/bin/apt-get'
	alias apt-cache-no-proxy '/usr/bin/apt-cache'
	alias ssh-no-proxy '/usr/bin/ssh'
	alias w3m-no-proxy '/usr/bin/w3m'
end


if test -e /usr/bin/proxychains
	alias emacs 'proxychains emacsclient -c'
	alias emacs-client 'proxychains emacsclient -c'
	alias emacs-daemon 'proxychains /usr/bin/emacs --daemon'
else
	alias emacs 'emacsclient -c'
	alias emacs-client 'emacsclient -c'
	alias emacs-daemon '/usr/bin/emacs --daemon'
end
